################################################
# Copyright (c) 2015-2019 Intel Corporation.
# All rights reserved.
#
# SPDX-License-Identidfier: Apache-2.0
#
################################################

CSOURCES = $(wildcard *.c)
ASOURCES = $(wildcard *.S)

INCLUDES = -I./include
CFLAGS += $(INCLUDES)

include $(PROJS)/rule.linux
