################################################
# Copyright (c) 2015-2019 Intel Corporation.
# All rights reserved.
#
# SPDX-License-Identidfier: Apache-2.0
#
################################################

export OUTDIR = $(BUILD_DIR)common

$(shell mkdir -p $(OUTDIR))

CSOURCES = $(wildcard *.c)
ASOURCES = $(wildcard *.S)

include $(PROJS)/rule.linux
