################################################
# Copyright (c) 2018 Intel Corporation.
# All rights reserved.
#
# SPDX-License-Identidfier: Apache-2.0
#
################################################

CSOURCES = $(wildcard *.c)
include $(PROJS)/rule.linux
