################################################
# Copyright (c) 2015-2019 Intel Corporation.
# All rights reserved.
#
# SPDX-License-Identidfier: Apache-2.0
#
################################################

SUBDIRS = mbedtls

CSOURCES = $(wildcard *.c)

include $(PROJS)/rule.linux
