#! /bin/sh
set -e

# grub-mkconfig helper script.
# Copyright (C) 2006,2007,2008,2009,2010  Free Software Foundation, Inc.
#
# GRUB is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GRUB is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GRUB.  If not, see <http://www.gnu.org/licenses/>.

prefix=/usr
exec_prefix=${prefix}
bindir=${exec_prefix}/bin
libdir=${exec_prefix}/lib
if test -e /usr/share/grub/grub-mkconfig_lib; then
  . /usr/share/grub/grub-mkconfig_lib
elif test -e ${libdir}/grub/grub-mkconfig_lib; then
  . ${libdir}/grub/grub-mkconfig_lib
fi

export TEXTDOMAIN=grub
export TEXTDOMAINDIR=${prefix}/share/locale

CLASS="--class gnu-linux --class gnu --class os --class iKGT"

if [ "x${GRUB_DISTRIBUTOR}" = "x" ] ; then
    OS=GNU/Linux
else
    OS="${GRUB_DISTRIBUTOR} GNU/Linux"
    CLASS="--class $(echo ${GRUB_DISTRIBUTOR} | tr '[A-Z]' '[a-z]' | cut -d' ' -f1) ${CLASS}"
fi

# loop-AES arranges things so that /dev/loop/X can be our root device, but
# the initrds that Linux uses don't like that.
case ${GRUB_DEVICE} in
    /dev/loop/*|/dev/loop[0-9])
    GRUB_DEVICE=`losetup ${GRUB_DEVICE} | sed -e "s/^[^(]*(\([^)]\+\)).*/\1/"`
    ;;
esac

if [ "x${GRUB_DEVICE_UUID}" = "x" ] || [ "x${GRUB_DISABLE_LINUX_UUID}" = "xtrue" ] \
    || ! test -e "/dev/disk/by-uuid/${GRUB_DEVICE_UUID}" \
    || uses_abstraction "${GRUB_DEVICE}" lvm; then
    LINUX_ROOT_DEVICE=${GRUB_DEVICE}
else
    LINUX_ROOT_DEVICE=UUID=${GRUB_DEVICE_UUID}
fi

linux_entry ()
{
    os="$1"
    version="$2"
    ikgt_version="$3"
    recovery="$4"
    args="$5"
    ikgt_args="$6"

    if ${recovery} ; then
        title="$(gettext_quoted "%s, with iKGT %s and Linux %s (recovery mode)")"
    else
        title="$(gettext_quoted "%s, with iKGT %s and Linux %s")"
    fi

    if [ -d /sys/firmware/efi ] ; then
        mb_directive="multiboot2"
        mb_mod_directive="module2"
        mb_extra_kernel="noefi"
    else
        mb_directive="multiboot"
        mb_mod_directive="module"
        mb_extra_kernel=""
    fi

    printf "menuentry '${title}' ${CLASS} {\n" "${os}" "${ikgt_version}" "${version}"
    if ! ${recovery} ; then
        save_default_entry | sed -e "s/^/\t/"
    fi
    #Enable below insmod when support MB2
    #if [ -d /sys/firmware/efi ] ; then
        #printf "\tinsmod multiboot2\n"
    #fi
    if [ -z "${prepare_boot_cache}" ]; then
        prepare_boot_cache="$(prepare_grub_to_access_device ${GRUB_DEVICE_BOOT} | sed -e "s/^/\t/")"
    fi
    printf '%s\n' "${prepare_boot_cache}"
    xmessage="$(gettext_printf "Loading iKGT %s ..." ${ikgt_version})"
    lmessage="$(gettext_printf "Loading Linux %s ..." ${version})"
    cat << EOF
	echo '$xmessage'
	${mb_directive} ${rel_ikgt_dirname}/${ikgt_basename} ${rel_ikgt_dirname}/${ikgt_basename} ${ikgt_args}
	echo '$lmessage'
EOF
    if test -d /sys/firmware/efi && test -e "${linux}.efi.signed"; then
        cat << EOF
	${mb_mod_directive} ${rel_dirname}/${basename}.efi.signed ${rel_dirname}/${basename} root=${linux_root_device_thisversion} ro ${args} ${mb_extra_kernel}
EOF
    else
        cat << EOF
	${mb_mod_directive} ${rel_dirname}/${basename} ${rel_dirname}/${basename} root=${linux_root_device_thisversion} ro ${args} ${mb_extra_kernel}
EOF
    fi
    if test -n "${initrd}" ; then
        message="$(gettext_printf "Loading initial ramdisk ...")"
        cat << EOF
	echo '$message'
	${mb_mod_directive} ${rel_dirname}/${initrd} ${rel_dirname}/${initrd}
EOF
    fi
    cat << EOF
}
EOF
}

linux_list=`for i in /boot/vmlinu[xz]-* /vmlinu[xz]-* ; do
    basename=$(basename $i)
    version=$(echo $basename | sed -e "s,^[^0-9]*-,,g")
        if grub_file_is_not_garbage "$i" ; then echo -n "$i " ; fi
    done`
ikgt_list=`for i in /boot/ikgt*.bin; do
        if grub_file_is_not_garbage "$i" ; then echo -n "$i " ; fi
    done`
prepare_boot_cache=

while [ "x${ikgt_list}" != "x" ] && [ "x$linux_list" != "x" ] ; do
    list="${linux_list}"
    current_ikgt=`version_find_latest $ikgt_list`
    ikgt_basename=`basename ${current_ikgt}`
    ikgt_dirname=`dirname ${current_ikgt}`
    rel_ikgt_dirname=`make_system_path_relative_to_its_root $ikgt_dirname`
#   ikgt_version=`echo $ikgt_basename | sed -e "s,.bin$,,g;s,^ikgt-,,g"`
    echo "submenu \"${OS}, with iKGT\" {"
    while [ "x$list" != "x" ] ; do
    linux=`version_find_latest $list`
    case $linux in
        *.efi.signed)
        #we handle these in linux_entry
        list=`echo $list | tr ' ' '\n' | grep -vx $linux | tr '\n' ' '`
        continue;
        ;;
    esac
    echo "Found linux image: $linux" >&2
    basename=`basename $linux`
    dirname=`dirname $linux`
    rel_dirname=`make_system_path_relative_to_its_root $dirname`
    version=`echo $basename | sed -e "s,^[^0-9]*-,,g"`
    alt_version=`echo $version | sed -e "s,\.old$,,g"`
    linux_root_device_thisversion="${LINUX_ROOT_DEVICE}"

    initrd=
    for i in "initrd.img-${version}" "initrd-${version}.img" \
            "initrd-${version}" "initramfs-${version}.img" \
            "initrd.img-${alt_version}" "initrd-${alt_version}.img" \
            "initrd-${alt_version}" "initramfs-${alt_version}.img" \
            "initramfs-genkernel-${version}" \
            "initramfs-genkernel-${alt_version}"; do
        if test -e "${dirname}/${i}" ; then
        initrd="$i"
        break
        fi
    done
    if test -n "${initrd}" ; then
        echo "Found initrd image: ${dirname}/${initrd}" >&2
    else
    # "UUID=" magic is parsed by initrds.  Since there's no initrd, it can't work here.
        linux_root_device_thisversion=${GRUB_DEVICE}
    fi

# Not support log for now
    if [ -d /sys/firmware/efi ] ; then
        ikgt_log=""
    else
        ikgt_log=""
    fi

    linux_entry "${OS}" "${version}" "${ikgt_version}" false \
        "${GRUB_CMDLINE_LINUX} ${GRUB_CMDLINE_LINUX_DEFAULT}" ${ikgt_log}
    if [ "x${GRUB_DISABLE_RECOVERY}" != "xtrue" ]; then
        linux_entry "${OS}" "${version}" "${ikgt_version}" true \
        "single ${GRUB_CMDLINE_LINUX}" ${ikgt_log}
    fi

    list=`echo $list | tr ' ' '\n' | grep -vx $linux | tr '\n' ' '`
    done
    echo "}"
    ikgt_list=`echo $ikgt_list | tr ' ' '\n' | grep -vx $current_ikgt | tr '\n' ' '`
done
